base_url = "https://wantguns.dev"
description = "Gunwant Jain's (@wantguns) writings and musings"
title = "Gunwant Jain - @wantguns"

compile_sass = true
generate_feeds = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]

[markdown.highlighting]
extra_themes = ["highlight_theme/base16-black-metal-bathory.json"]
theme = "base16-black-metal-bathory"

[extra]
author = "Gunwant Jain"
keywords = "Gunwant Jain, wantguns, Gunwant, WantGuns"
seo = true

nav_links = [
  {url = "$BASE_URL/about", name = "about"},
  {url = "$BASE_URL", name = "blog"},
  {url = "$BASE_URL/tags", name = "tags"},
  {url = "https://bin.wantguns.dev/cv", name = "resume"},
  {url = "$BASE_URL/atom.xml", name = "rss"},
]
