on: push

name: Build CI
jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_ONLY: true